[package]
name = "pam_omarchy_presence_unlock"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
nix = { workspace = true, features = ["user"] }
omarchy-presence-unlock-protocol = { path = "../protocol", default-features = false }
pam.workspace = true
