[package]
name = "omarchy-watch-unlock"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
btmgmt.workspace = true
console.workspace = true
dialoguer.workspace = true
futures-util.workspace = true
bluer.workspace = true
clap.workspace = true
nix.workspace = true
omarchy-watch-unlock-protocol = { path = "../protocol" }
rpassword.workspace = true
tokio.workspace = true
toml_edit.workspace = true
uuid.workspace = true
