[package]
name = "omarchy-presence-unlock"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
btmgmt.workspace = true
console.workspace = true
futures-util.workspace = true
bluer.workspace = true
clap.workspace = true
nix.workspace = true
omarchy-presence-unlock-protocol = { path = "../protocol" }
rpassword.workspace = true
shell-words.workspace = true
tokio.workspace = true
toml_edit.workspace = true
uuid.workspace = true
